[package]
name = "rusty_pall"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.20.1", default-features = false, features = ["std", "ndarray", "wgpu"] }
burn-store = { version = "0.20.1", default-features = false, features = ["std", "pytorch"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
